export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const FETCH_PROJECTS_FULFILLED = "FETCH_PROJECTS_FULFILLED";
export const FETCH_PROJECTS_REJECTED = "FETCH_PROJECTS_REJECTED";
export const FETCH_PROJECTS_PENDING = "FETCH_PROJECTS_PENDING";

export const FETCH_PROJECT = "FETCH_PROJECT";
export const FETCH_PROJECT_FULFILLED = "FETCH_PROJECT_FULFILLED";
export const FETCH_PROJECT_REJECTED = "FETCH_PROJECT_REJECTED";
export const FETCH_PROJECT_PENDING = "FETCH_PROJECT_PENDING";

export const ADD_PROJECT = "ADD_PROJECT";
export const ADD_PROJECT_FULFILLED = "ADD_PROJECT_FULFILLED";
export const ADD_PROJECT_REJECTED = "ADD_PROJECT_REJECTED";
export const ADD_PROJECT_PENDING = "ADD_PROJECT_PENDING";

export const REMOVE_PROJECT = "REMOVE_PROJECT";
export const REMOVE_PROJECT_FULFILLED = "REMOVE_PROJECT_FULFILLED";
export const REMOVE_PROJECT_REJECTED = "REMOVE_PROJECT_REJECTED";
export const REMOVE_PROJECT_PENDING = "REMOVE_PROJECT_PENDING";

export const EDIT_PROJECT = "EDIT_PROJECT";
export const EDIT_PROJECT_FULFILLED = "EDIT_PROJECT_FULFILLED";
export const EDIT_PROJECT_REJECTED = "EDIT_PROJECT_REJECTED";
export const EDIT_PROJECT_PENDING = "EDIT_PROJECT_PENDING";
